### ISSUE TITLE
crowvoorhees - tracking workflow progress

### ISSUE THREAD

**Issue by crowvoorhees** [githubteacher/developers-august-2016#13]
### workflow
- [ ] create a branch
- [ ] make commits on a new branch
- [ ] open a pull request
- [ ] collaborate
- [ ] make more commits
- [ ] merge into master
