### ISSUE TITLE
fjm - tracking workflow progress

### ISSUE THREAD

**Issue by fjmurray** [githubteacher/developers-august-2016#18]
# Workflow
- [x] Create a branch
- [x] Make commits on new branch
- [x] Open a PR (Pull Request)
- [x] Collaborate
- [x] Make  more commits
- [x] Merge into master
