### ISSUE TITLE
@codeangler  - tracking workflow 

### ISSUE THREAD

**Issue by codeangler** [githubteacher/developers-august-2016#22]
# Workflow
- [x] Create a branch
- [x] Make commits on new branch
- [x] Open a pull request
- [ ] Collaborate 🎉 
- [ ] Make more commits
- [ ] Merge into master
