### ISSUE TITLE
jenmacchiarelli - tracking workflow progress

### ISSUE THREAD

**Issue by jenmacchiarelli** [githubteacher/developers-august-2016#26]
# Workflow
- [x] Create a branch
- [x] Make commits on new branch
- [ ] Open a pull request
- [ ] Collaborate 🎉 
- [ ] Make more commits
- [ ] Merge into master

🍕 🍕
