### ISSUE TITLE
anton - tracking new issues

### ISSUE THREAD

**Issue by antonvalderrama** [githubteacher/developers-august-2016#28]
- [x] Create a branch
- [ ] Make commits on new branch
- [ ] Open a pull request
- [ ] Collaborate 🎉 
- [ ] Make more commits
- [ ] Merge into master
