### ISSUE TITLE
RandyisaBeast - tracking beastly progress

### ISSUE THREAD

**Issue by randyfrench5** [githubteacher/developers-august-2016#33]
# Workflow
- [x] Create a branch
- [x] Make commits on new branch
- [ ] Open a pull request
- [ ] Collaborate 🎉 
- [ ] Make more commits
- [ ] Merge into master

what do you think about these changes?
