### ISSUE TITLE
GitHubStudent - Tracking Workflow Process

### ISSUE THREAD

**Issue by Umesh29** [githubteacher/developers-august-2016#53]
# Workflow
- [ ] Create a branch
- [ ] Make commits on new branch
- [ ] Open a pull request
- [ ] Collaborate :tada: 
- [ ] Make more commits
- [ ] Merge into master

what do you think about these changes?
