### ISSUE TITLE
SirNexus- Tracking Training Progress

### ISSUE THREAD

**Issue by SirNexus** [githubteacher/developers-august-2016#7]
# Workflow
- [x] Create a branch
- [x] Make commits on new branch
- [x] Open a pull request
- [x] Collaborate 🎉 
- [ ] Make more commits
- [ ] Merge into master

**Comment by SirNexus** [comment]
Checklist for training
